### ISSUE TITLE
Employee Form

### ISSUE THREAD

**Issue by SharineAnkenbrand** [SharineAnkenbrand/capstone-project-21#1]
**Send a form to employees**

As a manager I want to send a basic form to my employees in order to plan the work schedule for the next day or for a special event.

**Acceptance criteria**

- [x]  Click on share button to send form

**Complexity**
L

**Tasks**

- [x]  Add employee form component
- [x]  Create and save employee form
- [x]  Link form via share button
