### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by SharineAnkenbrand** [SharineAnkenbrand/capstone-project-21#10]
**Calendar**

As a manager I want to select a specific date so that my employees know to which day I'm referring to.

**Acceptance criteria**

- [x]  User can click on calendar Icon on /home page 
- [x] Modal will show up as a calendar
 
**Complexity**
L

**Tasks**

- [x] Create calendar component
- [x] Implement select date logic
- [x] Display date on /employee-form and /work-schedule page
