### ISSUE TITLE
Work Schedule

### ISSUE THREAD

**Issue by SharineAnkenbrand** [SharineAnkenbrand/capstone-project-21#2]
**Plan the daily schedule**

As a manager I want to delete the registered employees so that I can plan easily the work schedule for the next day or for a special upcoming event.

**Acceptance criteria**

- [x]  Show table with assigned entries
- [x]  Manager can delete employees which aren't needed anymore

**Complexity**
L

**Tasks**

- [x]  Render entries in table
- [x]  Implement delete logic
