### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by SharineAnkenbrand** [SharineAnkenbrand/capstone-project-21#6]
**Navigate through different pages**

As a manager I want to navigate through different pages so that I can select the desired page that I want.

**Acceptance criteria**

- [x]  Click on home and calendar icon to switch pages

**Complexity**
S

**Tasks**

- [x]  Add navigation component
- [x]  Implement Router, NavLink
